# Site settings
title: Project Fluency
email: projectfluency@gmail.com
url: "http://projectfluency.org"
description: "Project Fluency is a new platform to make English speakers more confident. We support you to have better conversations in English, every day!"
summary: "Enabling Language Practice in Everyday Life"
logo: "/img/Logo.png"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Project Fluency

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Build settings
markdown: kramdown
permalink: pretty
