# Site settings
title: Project Fluency
email: projectfluency@gmail.com
url: "http://projectfluency.org"
description: "We are turning everyday workplace interactions into language learning opportunities."
logo: "/img/Logo.png"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Project Fluency

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Build settings
markdown: kramdown
permalink: pretty
